"""Generate kernel-checkable Lean certificates that the one-parameter family
    (0,2) (0,n-7) (1,13) (3,n-6) (4,31) (n-8,n-5)
is pancyclic on C_n for every n in 41..67, i.e. PancyclicWithChords n 6, in the
exact form Erdos1016/Excess2.lean and Erdos1016/Witness56.lean already use for
n = 56 (adjacency as a Bool function, one explicit vertex list per cycle length,
`isPancyclic_of_candidates` discharged by `decide`).

Writes Erdos1016/Family/W{n}.lean for each n, Erdos1016/Family.lean with the
range theorem `family_pancyclic_41_67`, and appends the import to Erdos1016.lean
and the axiom prints to Axioms.lean (idempotently).  Every emitted cycle is
re-checked here (distinct vertices, consecutive adjacency, closing edge) before
it is written; Lean re-checks all of it from scratch.
"""
from __future__ import annotations

import sys
from pathlib import Path

import networkx as nx

REPO = Path(__file__).resolve().parents[2]
FAM = REPO / "Erdos1016" / "Family"
LO, HI = 41, 67


def family(n):
    return [(0, 2), (0, n - 7), (1, 13), (3, n - 6), (4, 31), (n - 8, n - 5)]


def adjacent(n, chords, u, v):
    return v == (u + 1) % n or u == (v + 1) % n or (u, v) in chords or (v, u) in chords


def cycles_by_length(n, chords):
    g = nx.Graph()
    g.add_edges_from((i, (i + 1) % n) for i in range(n))
    g.add_edges_from(chords)
    best = {}
    for cyc in nx.simple_cycles(g):
        L = len(cyc)
        if 3 <= L <= n and L not in best:
            best[L] = list(cyc)
        if len(best) == n - 2:
            break
    missing = [L for L in range(3, n + 1) if L not in best]
    if missing:
        raise SystemExit(f"n={n}: no simple cycle of length(s) {missing}")
    chordset = set(chords)
    for L, cyc in best.items():
        assert len(cyc) == L and len(set(cyc)) == L
        for a, b in zip(cyc, cyc[1:] + cyc[:1]):
            assert adjacent(n, chordset, a, b), (n, L, a, b)
    return [best[L] for L in range(3, n + 1)]


def lean_file(n, chords, cycles):
    cs = ", ".join(f"({a},{b})" for a, b in chords)
    syms = ", ".join(f"s({a},{b})" for a, b in chords)
    cyc_lines = ",\n".join("  [" + ", ".join(str(v) for v in c) + "]" for c in cycles)
    rfl_cases = " | ".join(["rfl"] * len(chords))
    return f"""import Mathlib
import Erdos1016.Basic
import Erdos1016.Witness
import Erdos1016.ListCycle
import Erdos1016.Excess

/-!
Family member n = {n}: C_{n} plus the chords {cs} is pancyclic.
Generated by search/k6/gen_family_lean.py; the cycle lists are certificates only,
Lean re-derives every fact about them by `decide`.
-/

open SimpleGraph
namespace Erdos1016

def chordsF{n} : List (Nat × Nat) := [{cs}]
def adjF{n} (a b : Fin {n}) : Bool := adjB {n} chordsF{n} a.val b.val
def GF{n} : SimpleGraph (Fin {n}) :=
  SimpleGraph.fromRel (fun u v => adjB {n} chordsF{n} u.val v.val = true)
theorem adjF{n}_irrefl : ∀ a : Fin {n}, adjF{n} a a = false := by decide
theorem adjF{n}_spec (a b : Fin {n}) (h : adjF{n} a b = true) : GF{n}.Adj a b := by
  unfold GF{n}
  rw [SimpleGraph.fromRel_adj]
  refine ⟨fun hab => ?_, Or.inl h⟩
  subst hab
  rw [adjF{n}_irrefl] at h
  exact Bool.false_ne_true h

def cyclesF{n} : List (List Nat) := [
{cyc_lines}
]
def cyclesF{n}F : List (List (Fin {n})) :=
  cyclesF{n}.map (List.map (fun v : ℕ => (⟨v % {n}, Nat.mod_lt v (by decide)⟩ : Fin {n})))

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem candidatesF{n} : (List.range' 3 ({n} - 2)).all (fun ℓ => cyclesF{n}F.any (fun l =>
    (l.length == ℓ) && decide l.Nodup && chainB adjF{n} l && closesB adjF{n} l)) = true := by decide

theorem isPancyclic_GF{n} : IsPancyclic GF{n} :=
  isPancyclic_of_candidates GF{n} adjF{n} adjF{n}_spec cyclesF{n}F candidatesF{n}

def csF{n} : Finset (Sym2 (Fin {n})) := {{{syms}}}
set_option maxHeartbeats 0 in
theorem csF{n}_card : csF{n}.card = 6 := by decide

-- `decide` over all pairs of `Fin {n}`: the n = 56 template ran just inside the default
-- heartbeat and recursion limits, n >= 60 does not (W60/W64/W66 failed at these lines on
-- 2026-09-19 22:58), so both limits are lifted for this kernel computation.
set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem adjF{n}_iff (a b : Fin {n}) :
    (adjF{n} a b = true ∨ adjF{n} b a = true) ↔
      ((b.val = (a.val + 1) % {n} ∨ a.val = (b.val + 1) % {n}) ∨ s(a, b) ∈ csF{n}) := by
  revert a b
  decide

theorem GF{n}_eq : baseCycle {n} ⊔ SimpleGraph.fromEdgeSet (↑csF{n} : Set (Sym2 (Fin {n}))) = GF{n} := by
  ext a b
  simp only [SimpleGraph.sup_adj, baseCycle, GF{n}, SimpleGraph.fromRel_adj,
    SimpleGraph.fromEdgeSet_adj, Finset.mem_coe]
  have h := adjF{n}_iff a b
  unfold adjF{n} at h
  constructor
  · rintro (⟨hne, hc⟩ | ⟨hm, hne⟩)
    · exact ⟨hne, h.2 (Or.inl hc)⟩
    · exact ⟨hne, h.2 (Or.inr hm)⟩
  · rintro ⟨hne, hadj⟩
    rcases h.1 hadj with hc | hm
    · exact Or.inl ⟨hne, hc⟩
    · exact Or.inr ⟨hm, hne⟩

theorem csF{n}_disjoint : ∀ e ∈ csF{n}, e ∉ (baseCycle {n}).edgeSet := by
  intro e he
  simp only [csF{n}, Finset.mem_insert, Finset.mem_singleton] at he
  rcases he with {rfl_cases} <;>
    simp [SimpleGraph.mem_edgeSet, baseCycle, SimpleGraph.fromRel_adj]

/-- `h({n}) ≤ 6`, by the family member at n = {n}. -/
theorem pancyclicWithChords_F{n} : PancyclicWithChords {n} 6 :=
  ⟨csF{n}, csF{n}_card, csF{n}_disjoint, by rw [GF{n}_eq]; exact isPancyclic_GF{n}⟩

end Erdos1016
"""


def family_file(ns):
    imports = "\n".join(f"import Erdos1016.Family.W{n}" for n in ns)
    exacts = ", ".join(f"pancyclicWithChords_F{n}" for n in ns)
    return f"""{imports}

/-!
# `h(n) ≤ 6` for every `41 ≤ n ≤ 67`

The one-parameter family `(0,2) (0,n-7) (1,13) (3,n-6) (4,31) (n-8,n-5)` is pancyclic on
`C_n` at every `n` from {ns[0]} to {ns[-1]}; each member is certified in its own file
`Erdos1016/Family/W{{n}}.lean` (generated by `search/k6/gen_family_lean.py`).
-/

namespace Erdos1016

/-- The upper half of `h(n) = 6` on `41..67`: some set of six chords makes `C_n` pancyclic. -/
theorem family_pancyclic_41_67 : ∀ n : ℕ, {ns[0]} ≤ n → n ≤ {ns[-1]} → PancyclicWithChords n 6 := by
  intro n h1 h2
  interval_cases n
  exacts [{exacts}]

end Erdos1016
"""


def main():
    ns = list(range(LO, HI + 1))
    FAM.mkdir(parents=True, exist_ok=True)
    for n in ns:
        chords = family(n)
        cycles = cycles_by_length(n, chords)
        (FAM / f"W{n}.lean").write_text(lean_file(n, chords, cycles), encoding="utf-8", newline="\n")
        print(f"n={n}: {len(cycles)} cycle certificates written", flush=True)
    (REPO / "Erdos1016" / "Family.lean").write_text(family_file(ns), encoding="utf-8", newline="\n")
    root = REPO / "Erdos1016.lean"
    text = root.read_text(encoding="utf-8")
    if "import Erdos1016.Family\n" not in text:
        root.write_text(text.rstrip("\n") + "\nimport Erdos1016.Family\n", encoding="utf-8", newline="\n")
    ax = REPO / "Axioms.lean"
    text = ax.read_text(encoding="utf-8")
    lines = ["#print axioms Erdos1016.family_pancyclic_41_67"] + [f"#print axioms Erdos1016.pancyclicWithChords_F{n}" for n in ns]
    add = [l for l in lines if l not in text]
    if add:
        ax.write_text(text.rstrip("\n") + "\n-- The family (0,2)(0,n-7)(1,13)(3,n-6)(4,31)(n-8,n-5) at every n in 41..67.\n"
                      + "\n".join(add) + "\n", encoding="utf-8", newline="\n")
    print("done")


if __name__ == "__main__":
    sys.exit(main())
