import Erdos1016.Family.W41
import Erdos1016.Family.W42
import Erdos1016.Family.W43
import Erdos1016.Family.W44
import Erdos1016.Family.W45
import Erdos1016.Family.W46
import Erdos1016.Family.W47
import Erdos1016.Family.W48
import Erdos1016.Family.W49
import Erdos1016.Family.W50
import Erdos1016.Family.W51
import Erdos1016.Family.W52
import Erdos1016.Family.W53
import Erdos1016.Family.W54
import Erdos1016.Family.W55
import Erdos1016.Family.W56
import Erdos1016.Family.W57
import Erdos1016.Family.W58
import Erdos1016.Family.W59
import Erdos1016.Family.W60
import Erdos1016.Family.W61
import Erdos1016.Family.W62
import Erdos1016.Family.W63
import Erdos1016.Family.W64
import Erdos1016.Family.W65
import Erdos1016.Family.W66
import Erdos1016.Family.W67

/-!
# `h(n) ≤ 6` for every `41 ≤ n ≤ 67`

The one-parameter family `(0,2) (0,n-7) (1,13) (3,n-6) (4,31) (n-8,n-5)` is pancyclic on
`C_n` at every `n` from 41 to 67; each member is certified in its own file
`Erdos1016/Family/W{n}.lean` (generated by `search/k6/gen_family_lean.py`).
-/

namespace Erdos1016

/-- The upper half of `h(n) = 6` on `41..67`: some set of six chords makes `C_n` pancyclic. -/
theorem family_pancyclic_41_67 : ∀ n : ℕ, 41 ≤ n → n ≤ 67 → PancyclicWithChords n 6 := by
  intro n h1 h2
  interval_cases n
  exacts [pancyclicWithChords_F41, pancyclicWithChords_F42, pancyclicWithChords_F43, pancyclicWithChords_F44, pancyclicWithChords_F45, pancyclicWithChords_F46, pancyclicWithChords_F47, pancyclicWithChords_F48, pancyclicWithChords_F49, pancyclicWithChords_F50, pancyclicWithChords_F51, pancyclicWithChords_F52, pancyclicWithChords_F53, pancyclicWithChords_F54, pancyclicWithChords_F55, pancyclicWithChords_F56, pancyclicWithChords_F57, pancyclicWithChords_F58, pancyclicWithChords_F59, pancyclicWithChords_F60, pancyclicWithChords_F61, pancyclicWithChords_F62, pancyclicWithChords_F63, pancyclicWithChords_F64, pancyclicWithChords_F65, pancyclicWithChords_F66, pancyclicWithChords_F67]

end Erdos1016
