import Mathlib
import Erdos1016.Basic
import Erdos1016.Witness
import Erdos1016.ListCycle
import Erdos1016.Excess

/-!
Family member n = 41: C_41 plus the chords (0,2), (0,34), (1,13), (3,35), (4,31), (33,36) is pancyclic.
Generated by search/k6/gen_family_lean.py; the cycle lists are certificates only,
Lean re-derives every fact about them by `decide`.
-/

open SimpleGraph
namespace Erdos1016

def chordsF41 : List (Nat × Nat) := [(0,2), (0,34), (1,13), (3,35), (4,31), (33,36)]
def adjF41 (a b : Fin 41) : Bool := adjB 41 chordsF41 a.val b.val
def GF41 : SimpleGraph (Fin 41) :=
  SimpleGraph.fromRel (fun u v => adjB 41 chordsF41 u.val v.val = true)
theorem adjF41_irrefl : ∀ a : Fin 41, adjF41 a a = false := by decide
theorem adjF41_spec (a b : Fin 41) (h : adjF41 a b = true) : GF41.Adj a b := by
  unfold GF41
  rw [SimpleGraph.fromRel_adj]
  refine ⟨fun hab => ?_, Or.inl h⟩
  subst hab
  rw [adjF41_irrefl] at h
  exact Bool.false_ne_true h

def cyclesF41 : List (List Nat) := [
  [0, 1, 2],
  [34, 33, 36, 35],
  [0, 2, 3, 35, 34],
  [0, 1, 2, 3, 35, 34],
  [0, 2, 3, 35, 36, 33, 34],
  [0, 1, 2, 3, 35, 36, 33, 34],
  [0, 1, 2, 3, 4, 31, 32, 33, 34],
  [0, 1, 2, 3, 35, 36, 37, 38, 39, 40],
  [0, 1, 2, 3, 4, 31, 32, 33, 36, 35, 34],
  [0, 1, 2, 3, 35, 34, 33, 36, 37, 38, 39, 40],
  [0, 1, 2, 3, 4, 31, 32, 33, 36, 37, 38, 39, 40],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 35, 36, 33, 34],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 36, 35, 34],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 35, 36, 37, 38, 39, 40],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 36, 37, 38, 39, 40],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 35, 34, 33, 36, 37, 38, 39, 40],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  [0, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 35, 34],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 36, 35, 34],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 35, 36, 33, 34],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 36, 37, 38, 39, 40],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 35, 36, 37, 38, 39, 40],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 35, 34, 33, 36, 37, 38, 39, 40],
  [0, 40, 39, 38, 37, 36, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2, 3, 35, 34],
  [34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 35],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 36, 35, 34],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 36, 35, 34],
  [0, 40, 39, 38, 37, 36, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 36, 37, 38, 39, 40],
  [0, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
]
def cyclesF41F : List (List (Fin 41)) :=
  cyclesF41.map (List.map (fun v : ℕ => (⟨v % 41, Nat.mod_lt v (by decide)⟩ : Fin 41)))

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem candidatesF41 : (List.range' 3 (41 - 2)).all (fun ℓ => cyclesF41F.any (fun l =>
    (l.length == ℓ) && decide l.Nodup && chainB adjF41 l && closesB adjF41 l)) = true := by decide

theorem isPancyclic_GF41 : IsPancyclic GF41 :=
  isPancyclic_of_candidates GF41 adjF41 adjF41_spec cyclesF41F candidatesF41

def csF41 : Finset (Sym2 (Fin 41)) := {s(0,2), s(0,34), s(1,13), s(3,35), s(4,31), s(33,36)}
set_option maxHeartbeats 0 in
theorem csF41_card : csF41.card = 6 := by decide

-- `decide` over all pairs of `Fin 41`: the n = 56 template ran just inside the default
-- heartbeat and recursion limits, n >= 60 does not (W60/W64/W66 failed at these lines on
-- 2026-09-19 22:58), so both limits are lifted for this kernel computation.
set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem adjF41_iff (a b : Fin 41) :
    (adjF41 a b = true ∨ adjF41 b a = true) ↔
      ((b.val = (a.val + 1) % 41 ∨ a.val = (b.val + 1) % 41) ∨ s(a, b) ∈ csF41) := by
  revert a b
  decide

theorem GF41_eq : baseCycle 41 ⊔ SimpleGraph.fromEdgeSet (↑csF41 : Set (Sym2 (Fin 41))) = GF41 := by
  ext a b
  simp only [SimpleGraph.sup_adj, baseCycle, GF41, SimpleGraph.fromRel_adj,
    SimpleGraph.fromEdgeSet_adj, Finset.mem_coe]
  have h := adjF41_iff a b
  unfold adjF41 at h
  constructor
  · rintro (⟨hne, hc⟩ | ⟨hm, hne⟩)
    · exact ⟨hne, h.2 (Or.inl hc)⟩
    · exact ⟨hne, h.2 (Or.inr hm)⟩
  · rintro ⟨hne, hadj⟩
    rcases h.1 hadj with hc | hm
    · exact Or.inl ⟨hne, hc⟩
    · exact Or.inr ⟨hm, hne⟩

theorem csF41_disjoint : ∀ e ∈ csF41, e ∉ (baseCycle 41).edgeSet := by
  intro e he
  simp only [csF41, Finset.mem_insert, Finset.mem_singleton] at he
  rcases he with rfl | rfl | rfl | rfl | rfl | rfl <;>
    simp [SimpleGraph.mem_edgeSet, baseCycle, SimpleGraph.fromRel_adj]

/-- `h(41) ≤ 6`, by the family member at n = 41. -/
theorem pancyclicWithChords_F41 : PancyclicWithChords 41 6 :=
  ⟨csF41, csF41_card, csF41_disjoint, by rw [GF41_eq]; exact isPancyclic_GF41⟩

end Erdos1016
