import Mathlib
import Erdos1016.Basic
import Erdos1016.Witness
import Erdos1016.ListCycle
import Erdos1016.Excess

/-!
Family member n = 43: C_43 plus the chords (0,2), (0,36), (1,13), (3,37), (4,31), (35,38) is pancyclic.
Generated by search/k6/gen_family_lean.py; the cycle lists are certificates only,
Lean re-derives every fact about them by `decide`.
-/

open SimpleGraph
namespace Erdos1016

def chordsF43 : List (Nat × Nat) := [(0,2), (0,36), (1,13), (3,37), (4,31), (35,38)]
def adjF43 (a b : Fin 43) : Bool := adjB 43 chordsF43 a.val b.val
def GF43 : SimpleGraph (Fin 43) :=
  SimpleGraph.fromRel (fun u v => adjB 43 chordsF43 u.val v.val = true)
theorem adjF43_irrefl : ∀ a : Fin 43, adjF43 a a = false := by decide
theorem adjF43_spec (a b : Fin 43) (h : adjF43 a b = true) : GF43.Adj a b := by
  unfold GF43
  rw [SimpleGraph.fromRel_adj]
  refine ⟨fun hab => ?_, Or.inl h⟩
  subst hab
  rw [adjF43_irrefl] at h
  exact Bool.false_ne_true h

def cyclesF43 : List (List Nat) := [
  [0, 1, 2],
  [36, 35, 38, 37],
  [0, 2, 3, 37, 36],
  [0, 1, 2, 3, 37, 36],
  [0, 2, 3, 37, 38, 35, 36],
  [0, 1, 2, 3, 37, 38, 35, 36],
  [0, 42, 41, 40, 39, 38, 37, 3, 2],
  [0, 1, 2, 3, 37, 38, 39, 40, 41, 42],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36],
  [0, 1, 2, 3, 37, 36, 35, 38, 39, 40, 41, 42],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 38, 37, 36],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 38, 39, 40, 41, 42],
  [0, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 4, 3, 2],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 37, 38, 39, 40, 41, 42],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 38, 37, 36],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 37, 36, 35, 38, 39, 40, 41, 42],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 38, 39, 40, 41, 42],
  [0, 42, 41, 40, 39, 38, 35, 34, 33, 32, 31, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 37, 36],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 37, 38, 35, 36],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 38, 37, 36],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 37, 38, 39, 40, 41, 42],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 38, 39, 40, 41, 42],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 37, 36, 35, 38, 39, 40, 41, 42],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
  [0, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 42, 41, 40, 39, 38, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2, 3, 37, 36],
  [36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 37],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 38, 37, 36],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 38, 37, 36],
  [0, 42, 41, 40, 39, 38, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 38, 39, 40, 41, 42],
  [0, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]
]
def cyclesF43F : List (List (Fin 43)) :=
  cyclesF43.map (List.map (fun v : ℕ => (⟨v % 43, Nat.mod_lt v (by decide)⟩ : Fin 43)))

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem candidatesF43 : (List.range' 3 (43 - 2)).all (fun ℓ => cyclesF43F.any (fun l =>
    (l.length == ℓ) && decide l.Nodup && chainB adjF43 l && closesB adjF43 l)) = true := by decide

theorem isPancyclic_GF43 : IsPancyclic GF43 :=
  isPancyclic_of_candidates GF43 adjF43 adjF43_spec cyclesF43F candidatesF43

def csF43 : Finset (Sym2 (Fin 43)) := {s(0,2), s(0,36), s(1,13), s(3,37), s(4,31), s(35,38)}
set_option maxHeartbeats 0 in
theorem csF43_card : csF43.card = 6 := by decide

-- `decide` over all pairs of `Fin 43`: the n = 56 template ran just inside the default
-- heartbeat and recursion limits, n >= 60 does not (W60/W64/W66 failed at these lines on
-- 2026-09-19 22:58), so both limits are lifted for this kernel computation.
set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem adjF43_iff (a b : Fin 43) :
    (adjF43 a b = true ∨ adjF43 b a = true) ↔
      ((b.val = (a.val + 1) % 43 ∨ a.val = (b.val + 1) % 43) ∨ s(a, b) ∈ csF43) := by
  revert a b
  decide

theorem GF43_eq : baseCycle 43 ⊔ SimpleGraph.fromEdgeSet (↑csF43 : Set (Sym2 (Fin 43))) = GF43 := by
  ext a b
  simp only [SimpleGraph.sup_adj, baseCycle, GF43, SimpleGraph.fromRel_adj,
    SimpleGraph.fromEdgeSet_adj, Finset.mem_coe]
  have h := adjF43_iff a b
  unfold adjF43 at h
  constructor
  · rintro (⟨hne, hc⟩ | ⟨hm, hne⟩)
    · exact ⟨hne, h.2 (Or.inl hc)⟩
    · exact ⟨hne, h.2 (Or.inr hm)⟩
  · rintro ⟨hne, hadj⟩
    rcases h.1 hadj with hc | hm
    · exact Or.inl ⟨hne, hc⟩
    · exact Or.inr ⟨hm, hne⟩

theorem csF43_disjoint : ∀ e ∈ csF43, e ∉ (baseCycle 43).edgeSet := by
  intro e he
  simp only [csF43, Finset.mem_insert, Finset.mem_singleton] at he
  rcases he with rfl | rfl | rfl | rfl | rfl | rfl <;>
    simp [SimpleGraph.mem_edgeSet, baseCycle, SimpleGraph.fromRel_adj]

/-- `h(43) ≤ 6`, by the family member at n = 43. -/
theorem pancyclicWithChords_F43 : PancyclicWithChords 43 6 :=
  ⟨csF43, csF43_card, csF43_disjoint, by rw [GF43_eq]; exact isPancyclic_GF43⟩

end Erdos1016
