import Mathlib
import Erdos1016.Basic
import Erdos1016.Witness
import Erdos1016.ListCycle
import Erdos1016.Excess

/-!
Family member n = 44: C_44 plus the chords (0,2), (0,37), (1,13), (3,38), (4,31), (36,39) is pancyclic.
Generated by search/k6/gen_family_lean.py; the cycle lists are certificates only,
Lean re-derives every fact about them by `decide`.
-/

open SimpleGraph
namespace Erdos1016

def chordsF44 : List (Nat × Nat) := [(0,2), (0,37), (1,13), (3,38), (4,31), (36,39)]
def adjF44 (a b : Fin 44) : Bool := adjB 44 chordsF44 a.val b.val
def GF44 : SimpleGraph (Fin 44) :=
  SimpleGraph.fromRel (fun u v => adjB 44 chordsF44 u.val v.val = true)
theorem adjF44_irrefl : ∀ a : Fin 44, adjF44 a a = false := by decide
theorem adjF44_spec (a b : Fin 44) (h : adjF44 a b = true) : GF44.Adj a b := by
  unfold GF44
  rw [SimpleGraph.fromRel_adj]
  refine ⟨fun hab => ?_, Or.inl h⟩
  subst hab
  rw [adjF44_irrefl] at h
  exact Bool.false_ne_true h

def cyclesF44 : List (List Nat) := [
  [0, 1, 2],
  [37, 36, 39, 38],
  [0, 2, 3, 38, 37],
  [0, 1, 2, 3, 38, 37],
  [0, 2, 3, 38, 39, 36, 37],
  [0, 1, 2, 3, 38, 39, 36, 37],
  [0, 43, 42, 41, 40, 39, 38, 3, 2],
  [0, 1, 2, 3, 38, 39, 40, 41, 42, 43],
  [0, 43, 42, 41, 40, 39, 36, 37, 38, 3, 2],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37],
  [0, 2, 3, 4, 31, 32, 33, 34, 35, 36, 39, 38, 37],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 39, 38, 37],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 38, 37],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 39, 40, 41, 42, 43],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 38, 39, 36, 37],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 38, 39, 40, 41, 42, 43],
  [0, 43, 42, 41, 40, 39, 38, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 38, 37, 36, 39, 40, 41, 42, 43],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 3, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 39, 40, 41, 42, 43],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
  [0, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 38, 39, 36, 37],
  [0, 2, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 38, 39, 36, 37],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 38, 39, 40, 41, 42, 43],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 3, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 38, 37, 36, 39, 40, 41, 42, 43],
  [0, 43, 42, 41, 40, 39, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
  [0, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 43, 42, 41, 40, 39, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2, 3, 38, 37],
  [37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 38],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 39, 38, 37],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 39, 38, 37],
  [0, 43, 42, 41, 40, 39, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 39, 40, 41, 42, 43],
  [0, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]
]
def cyclesF44F : List (List (Fin 44)) :=
  cyclesF44.map (List.map (fun v : ℕ => (⟨v % 44, Nat.mod_lt v (by decide)⟩ : Fin 44)))

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem candidatesF44 : (List.range' 3 (44 - 2)).all (fun ℓ => cyclesF44F.any (fun l =>
    (l.length == ℓ) && decide l.Nodup && chainB adjF44 l && closesB adjF44 l)) = true := by decide

theorem isPancyclic_GF44 : IsPancyclic GF44 :=
  isPancyclic_of_candidates GF44 adjF44 adjF44_spec cyclesF44F candidatesF44

def csF44 : Finset (Sym2 (Fin 44)) := {s(0,2), s(0,37), s(1,13), s(3,38), s(4,31), s(36,39)}
set_option maxHeartbeats 0 in
theorem csF44_card : csF44.card = 6 := by decide

-- `decide` over all pairs of `Fin 44`: the n = 56 template ran just inside the default
-- heartbeat and recursion limits, n >= 60 does not (W60/W64/W66 failed at these lines on
-- 2026-09-19 22:58), so both limits are lifted for this kernel computation.
set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem adjF44_iff (a b : Fin 44) :
    (adjF44 a b = true ∨ adjF44 b a = true) ↔
      ((b.val = (a.val + 1) % 44 ∨ a.val = (b.val + 1) % 44) ∨ s(a, b) ∈ csF44) := by
  revert a b
  decide

theorem GF44_eq : baseCycle 44 ⊔ SimpleGraph.fromEdgeSet (↑csF44 : Set (Sym2 (Fin 44))) = GF44 := by
  ext a b
  simp only [SimpleGraph.sup_adj, baseCycle, GF44, SimpleGraph.fromRel_adj,
    SimpleGraph.fromEdgeSet_adj, Finset.mem_coe]
  have h := adjF44_iff a b
  unfold adjF44 at h
  constructor
  · rintro (⟨hne, hc⟩ | ⟨hm, hne⟩)
    · exact ⟨hne, h.2 (Or.inl hc)⟩
    · exact ⟨hne, h.2 (Or.inr hm)⟩
  · rintro ⟨hne, hadj⟩
    rcases h.1 hadj with hc | hm
    · exact Or.inl ⟨hne, hc⟩
    · exact Or.inr ⟨hm, hne⟩

theorem csF44_disjoint : ∀ e ∈ csF44, e ∉ (baseCycle 44).edgeSet := by
  intro e he
  simp only [csF44, Finset.mem_insert, Finset.mem_singleton] at he
  rcases he with rfl | rfl | rfl | rfl | rfl | rfl <;>
    simp [SimpleGraph.mem_edgeSet, baseCycle, SimpleGraph.fromRel_adj]

/-- `h(44) ≤ 6`, by the family member at n = 44. -/
theorem pancyclicWithChords_F44 : PancyclicWithChords 44 6 :=
  ⟨csF44, csF44_card, csF44_disjoint, by rw [GF44_eq]; exact isPancyclic_GF44⟩

end Erdos1016
