import Mathlib
import Erdos1016.Basic
import Erdos1016.Witness
import Erdos1016.ListCycle
import Erdos1016.Excess

/-!
Family member n = 45: C_45 plus the chords (0,2), (0,38), (1,13), (3,39), (4,31), (37,40) is pancyclic.
Generated by search/k6/gen_family_lean.py; the cycle lists are certificates only,
Lean re-derives every fact about them by `decide`.
-/

open SimpleGraph
namespace Erdos1016

def chordsF45 : List (Nat × Nat) := [(0,2), (0,38), (1,13), (3,39), (4,31), (37,40)]
def adjF45 (a b : Fin 45) : Bool := adjB 45 chordsF45 a.val b.val
def GF45 : SimpleGraph (Fin 45) :=
  SimpleGraph.fromRel (fun u v => adjB 45 chordsF45 u.val v.val = true)
theorem adjF45_irrefl : ∀ a : Fin 45, adjF45 a a = false := by decide
theorem adjF45_spec (a b : Fin 45) (h : adjF45 a b = true) : GF45.Adj a b := by
  unfold GF45
  rw [SimpleGraph.fromRel_adj]
  refine ⟨fun hab => ?_, Or.inl h⟩
  subst hab
  rw [adjF45_irrefl] at h
  exact Bool.false_ne_true h

def cyclesF45 : List (List Nat) := [
  [0, 1, 2],
  [38, 37, 40, 39],
  [0, 2, 3, 39, 38],
  [0, 1, 2, 3, 39, 38],
  [0, 2, 3, 39, 40, 37, 38],
  [0, 1, 2, 3, 39, 40, 37, 38],
  [0, 44, 43, 42, 41, 40, 39, 3, 2],
  [0, 1, 2, 3, 39, 40, 41, 42, 43, 44],
  [0, 44, 43, 42, 41, 40, 37, 38, 39, 3, 2],
  [0, 1, 2, 3, 39, 38, 37, 40, 41, 42, 43, 44],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 40, 39, 38],
  [0, 44, 43, 42, 41, 40, 37, 36, 35, 34, 33, 32, 31, 4, 3, 2],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 40, 41, 42, 43, 44],
  [0, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 4, 3, 2],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 39, 38, 37, 40, 41, 42, 43, 44],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 40, 39, 38],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 3, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 40, 41, 42, 43, 44],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 39, 38],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 39, 40, 37, 38],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 39, 40, 41, 42, 43, 44],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 40, 39, 38],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 39, 38, 37, 40, 41, 42, 43, 44],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 40, 41, 42, 43, 44],
  [0, 44, 43, 42, 41, 40, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
  [0, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 44, 43, 42, 41, 40, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2, 3, 39, 38],
  [38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 39],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 40, 39, 38],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 40, 39, 38],
  [0, 44, 43, 42, 41, 40, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 40, 41, 42, 43, 44],
  [0, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]
]
def cyclesF45F : List (List (Fin 45)) :=
  cyclesF45.map (List.map (fun v : ℕ => (⟨v % 45, Nat.mod_lt v (by decide)⟩ : Fin 45)))

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem candidatesF45 : (List.range' 3 (45 - 2)).all (fun ℓ => cyclesF45F.any (fun l =>
    (l.length == ℓ) && decide l.Nodup && chainB adjF45 l && closesB adjF45 l)) = true := by decide

theorem isPancyclic_GF45 : IsPancyclic GF45 :=
  isPancyclic_of_candidates GF45 adjF45 adjF45_spec cyclesF45F candidatesF45

def csF45 : Finset (Sym2 (Fin 45)) := {s(0,2), s(0,38), s(1,13), s(3,39), s(4,31), s(37,40)}
set_option maxHeartbeats 0 in
theorem csF45_card : csF45.card = 6 := by decide

-- `decide` over all pairs of `Fin 45`: the n = 56 template ran just inside the default
-- heartbeat and recursion limits, n >= 60 does not (W60/W64/W66 failed at these lines on
-- 2026-09-19 22:58), so both limits are lifted for this kernel computation.
set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem adjF45_iff (a b : Fin 45) :
    (adjF45 a b = true ∨ adjF45 b a = true) ↔
      ((b.val = (a.val + 1) % 45 ∨ a.val = (b.val + 1) % 45) ∨ s(a, b) ∈ csF45) := by
  revert a b
  decide

theorem GF45_eq : baseCycle 45 ⊔ SimpleGraph.fromEdgeSet (↑csF45 : Set (Sym2 (Fin 45))) = GF45 := by
  ext a b
  simp only [SimpleGraph.sup_adj, baseCycle, GF45, SimpleGraph.fromRel_adj,
    SimpleGraph.fromEdgeSet_adj, Finset.mem_coe]
  have h := adjF45_iff a b
  unfold adjF45 at h
  constructor
  · rintro (⟨hne, hc⟩ | ⟨hm, hne⟩)
    · exact ⟨hne, h.2 (Or.inl hc)⟩
    · exact ⟨hne, h.2 (Or.inr hm)⟩
  · rintro ⟨hne, hadj⟩
    rcases h.1 hadj with hc | hm
    · exact Or.inl ⟨hne, hc⟩
    · exact Or.inr ⟨hm, hne⟩

theorem csF45_disjoint : ∀ e ∈ csF45, e ∉ (baseCycle 45).edgeSet := by
  intro e he
  simp only [csF45, Finset.mem_insert, Finset.mem_singleton] at he
  rcases he with rfl | rfl | rfl | rfl | rfl | rfl <;>
    simp [SimpleGraph.mem_edgeSet, baseCycle, SimpleGraph.fromRel_adj]

/-- `h(45) ≤ 6`, by the family member at n = 45. -/
theorem pancyclicWithChords_F45 : PancyclicWithChords 45 6 :=
  ⟨csF45, csF45_card, csF45_disjoint, by rw [GF45_eq]; exact isPancyclic_GF45⟩

end Erdos1016
