import Mathlib
import Erdos1016.Basic
import Erdos1016.Witness
import Erdos1016.ListCycle
import Erdos1016.Excess

/-!
Family member n = 46: C_46 plus the chords (0,2), (0,39), (1,13), (3,40), (4,31), (38,41) is pancyclic.
Generated by search/k6/gen_family_lean.py; the cycle lists are certificates only,
Lean re-derives every fact about them by `decide`.
-/

open SimpleGraph
namespace Erdos1016

def chordsF46 : List (Nat × Nat) := [(0,2), (0,39), (1,13), (3,40), (4,31), (38,41)]
def adjF46 (a b : Fin 46) : Bool := adjB 46 chordsF46 a.val b.val
def GF46 : SimpleGraph (Fin 46) :=
  SimpleGraph.fromRel (fun u v => adjB 46 chordsF46 u.val v.val = true)
theorem adjF46_irrefl : ∀ a : Fin 46, adjF46 a a = false := by decide
theorem adjF46_spec (a b : Fin 46) (h : adjF46 a b = true) : GF46.Adj a b := by
  unfold GF46
  rw [SimpleGraph.fromRel_adj]
  refine ⟨fun hab => ?_, Or.inl h⟩
  subst hab
  rw [adjF46_irrefl] at h
  exact Bool.false_ne_true h

def cyclesF46 : List (List Nat) := [
  [0, 1, 2],
  [39, 38, 41, 40],
  [0, 2, 3, 40, 39],
  [0, 1, 2, 3, 40, 39],
  [0, 2, 3, 40, 41, 38, 39],
  [0, 1, 2, 3, 40, 41, 38, 39],
  [0, 45, 44, 43, 42, 41, 40, 3, 2],
  [0, 1, 2, 3, 40, 41, 42, 43, 44, 45],
  [0, 45, 44, 43, 42, 41, 38, 39, 40, 3, 2],
  [0, 1, 2, 3, 40, 39, 38, 41, 42, 43, 44, 45],
  [0, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 40, 39],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 41, 40, 39],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 40, 41, 38, 39],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 41, 42, 43, 44, 45],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 40, 41, 42, 43, 44, 45],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 40, 39, 38, 41, 42, 43, 44, 45],
  [0, 45, 44, 43, 42, 41, 38, 39, 40, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 41, 40, 39],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 3, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 41, 42, 43, 44, 45],
  [0, 45, 44, 43, 42, 41, 38, 37, 36, 35, 34, 33, 32, 31, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  [0, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 40, 41, 42, 43, 44, 45],
  [0, 45, 44, 43, 42, 41, 40, 3, 4, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 40, 39, 38, 41, 42, 43, 44, 45],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 3, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 41, 42, 43, 44, 45],
  [0, 45, 44, 43, 42, 41, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  [0, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 45, 44, 43, 42, 41, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2, 3, 40, 39],
  [39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 40],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 41, 40, 39],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 41, 40, 39],
  [0, 45, 44, 43, 42, 41, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 41, 42, 43, 44, 45],
  [0, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]
]
def cyclesF46F : List (List (Fin 46)) :=
  cyclesF46.map (List.map (fun v : ℕ => (⟨v % 46, Nat.mod_lt v (by decide)⟩ : Fin 46)))

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem candidatesF46 : (List.range' 3 (46 - 2)).all (fun ℓ => cyclesF46F.any (fun l =>
    (l.length == ℓ) && decide l.Nodup && chainB adjF46 l && closesB adjF46 l)) = true := by decide

theorem isPancyclic_GF46 : IsPancyclic GF46 :=
  isPancyclic_of_candidates GF46 adjF46 adjF46_spec cyclesF46F candidatesF46

def csF46 : Finset (Sym2 (Fin 46)) := {s(0,2), s(0,39), s(1,13), s(3,40), s(4,31), s(38,41)}
set_option maxHeartbeats 0 in
theorem csF46_card : csF46.card = 6 := by decide

-- `decide` over all pairs of `Fin 46`: the n = 56 template ran just inside the default
-- heartbeat and recursion limits, n >= 60 does not (W60/W64/W66 failed at these lines on
-- 2026-09-19 22:58), so both limits are lifted for this kernel computation.
set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem adjF46_iff (a b : Fin 46) :
    (adjF46 a b = true ∨ adjF46 b a = true) ↔
      ((b.val = (a.val + 1) % 46 ∨ a.val = (b.val + 1) % 46) ∨ s(a, b) ∈ csF46) := by
  revert a b
  decide

theorem GF46_eq : baseCycle 46 ⊔ SimpleGraph.fromEdgeSet (↑csF46 : Set (Sym2 (Fin 46))) = GF46 := by
  ext a b
  simp only [SimpleGraph.sup_adj, baseCycle, GF46, SimpleGraph.fromRel_adj,
    SimpleGraph.fromEdgeSet_adj, Finset.mem_coe]
  have h := adjF46_iff a b
  unfold adjF46 at h
  constructor
  · rintro (⟨hne, hc⟩ | ⟨hm, hne⟩)
    · exact ⟨hne, h.2 (Or.inl hc)⟩
    · exact ⟨hne, h.2 (Or.inr hm)⟩
  · rintro ⟨hne, hadj⟩
    rcases h.1 hadj with hc | hm
    · exact Or.inl ⟨hne, hc⟩
    · exact Or.inr ⟨hm, hne⟩

theorem csF46_disjoint : ∀ e ∈ csF46, e ∉ (baseCycle 46).edgeSet := by
  intro e he
  simp only [csF46, Finset.mem_insert, Finset.mem_singleton] at he
  rcases he with rfl | rfl | rfl | rfl | rfl | rfl <;>
    simp [SimpleGraph.mem_edgeSet, baseCycle, SimpleGraph.fromRel_adj]

/-- `h(46) ≤ 6`, by the family member at n = 46. -/
theorem pancyclicWithChords_F46 : PancyclicWithChords 46 6 :=
  ⟨csF46, csF46_card, csF46_disjoint, by rw [GF46_eq]; exact isPancyclic_GF46⟩

end Erdos1016
