import Mathlib
import Erdos1016.Basic
import Erdos1016.Witness
import Erdos1016.ListCycle
import Erdos1016.Excess

/-!
Family member n = 47: C_47 plus the chords (0,2), (0,40), (1,13), (3,41), (4,31), (39,42) is pancyclic.
Generated by search/k6/gen_family_lean.py; the cycle lists are certificates only,
Lean re-derives every fact about them by `decide`.
-/

open SimpleGraph
namespace Erdos1016

def chordsF47 : List (Nat × Nat) := [(0,2), (0,40), (1,13), (3,41), (4,31), (39,42)]
def adjF47 (a b : Fin 47) : Bool := adjB 47 chordsF47 a.val b.val
def GF47 : SimpleGraph (Fin 47) :=
  SimpleGraph.fromRel (fun u v => adjB 47 chordsF47 u.val v.val = true)
theorem adjF47_irrefl : ∀ a : Fin 47, adjF47 a a = false := by decide
theorem adjF47_spec (a b : Fin 47) (h : adjF47 a b = true) : GF47.Adj a b := by
  unfold GF47
  rw [SimpleGraph.fromRel_adj]
  refine ⟨fun hab => ?_, Or.inl h⟩
  subst hab
  rw [adjF47_irrefl] at h
  exact Bool.false_ne_true h

def cyclesF47 : List (List Nat) := [
  [0, 1, 2],
  [40, 39, 42, 41],
  [0, 2, 3, 41, 40],
  [0, 1, 2, 3, 41, 40],
  [0, 2, 3, 41, 42, 39, 40],
  [0, 1, 2, 3, 41, 42, 39, 40],
  [0, 46, 45, 44, 43, 42, 41, 3, 2],
  [0, 1, 2, 3, 41, 42, 43, 44, 45, 46],
  [0, 46, 45, 44, 43, 42, 39, 40, 41, 3, 2],
  [0, 1, 2, 3, 41, 40, 39, 42, 43, 44, 45, 46],
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  [0, 2, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 41, 40],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 41, 40],
  [0, 46, 45, 44, 43, 42, 39, 38, 37, 36, 35, 34, 33, 32, 31, 4, 3, 2],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 43, 44, 45, 46],
  [0, 46, 45, 44, 43, 42, 41, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  [0, 2, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 41, 40],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 3, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 43, 44, 45, 46],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 41, 42, 39, 40],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 41, 42, 43, 44, 45, 46],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 41, 40, 39, 42, 43, 44, 45, 46],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 41, 40],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 3, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 43, 44, 45, 46],
  [0, 46, 45, 44, 43, 42, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
  [0, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 46, 45, 44, 43, 42, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2, 3, 41, 40],
  [40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 41],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 41, 40],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 41, 40],
  [0, 46, 45, 44, 43, 42, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 43, 44, 45, 46],
  [0, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46]
]
def cyclesF47F : List (List (Fin 47)) :=
  cyclesF47.map (List.map (fun v : ℕ => (⟨v % 47, Nat.mod_lt v (by decide)⟩ : Fin 47)))

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem candidatesF47 : (List.range' 3 (47 - 2)).all (fun ℓ => cyclesF47F.any (fun l =>
    (l.length == ℓ) && decide l.Nodup && chainB adjF47 l && closesB adjF47 l)) = true := by decide

theorem isPancyclic_GF47 : IsPancyclic GF47 :=
  isPancyclic_of_candidates GF47 adjF47 adjF47_spec cyclesF47F candidatesF47

def csF47 : Finset (Sym2 (Fin 47)) := {s(0,2), s(0,40), s(1,13), s(3,41), s(4,31), s(39,42)}
set_option maxHeartbeats 0 in
theorem csF47_card : csF47.card = 6 := by decide

-- `decide` over all pairs of `Fin 47`: the n = 56 template ran just inside the default
-- heartbeat and recursion limits, n >= 60 does not (W60/W64/W66 failed at these lines on
-- 2026-09-19 22:58), so both limits are lifted for this kernel computation.
set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem adjF47_iff (a b : Fin 47) :
    (adjF47 a b = true ∨ adjF47 b a = true) ↔
      ((b.val = (a.val + 1) % 47 ∨ a.val = (b.val + 1) % 47) ∨ s(a, b) ∈ csF47) := by
  revert a b
  decide

theorem GF47_eq : baseCycle 47 ⊔ SimpleGraph.fromEdgeSet (↑csF47 : Set (Sym2 (Fin 47))) = GF47 := by
  ext a b
  simp only [SimpleGraph.sup_adj, baseCycle, GF47, SimpleGraph.fromRel_adj,
    SimpleGraph.fromEdgeSet_adj, Finset.mem_coe]
  have h := adjF47_iff a b
  unfold adjF47 at h
  constructor
  · rintro (⟨hne, hc⟩ | ⟨hm, hne⟩)
    · exact ⟨hne, h.2 (Or.inl hc)⟩
    · exact ⟨hne, h.2 (Or.inr hm)⟩
  · rintro ⟨hne, hadj⟩
    rcases h.1 hadj with hc | hm
    · exact Or.inl ⟨hne, hc⟩
    · exact Or.inr ⟨hm, hne⟩

theorem csF47_disjoint : ∀ e ∈ csF47, e ∉ (baseCycle 47).edgeSet := by
  intro e he
  simp only [csF47, Finset.mem_insert, Finset.mem_singleton] at he
  rcases he with rfl | rfl | rfl | rfl | rfl | rfl <;>
    simp [SimpleGraph.mem_edgeSet, baseCycle, SimpleGraph.fromRel_adj]

/-- `h(47) ≤ 6`, by the family member at n = 47. -/
theorem pancyclicWithChords_F47 : PancyclicWithChords 47 6 :=
  ⟨csF47, csF47_card, csF47_disjoint, by rw [GF47_eq]; exact isPancyclic_GF47⟩

end Erdos1016
