import Mathlib
import Erdos1016.Basic
import Erdos1016.Witness
import Erdos1016.ListCycle
import Erdos1016.Excess

/-!
Family member n = 48: C_48 plus the chords (0,2), (0,41), (1,13), (3,42), (4,31), (40,43) is pancyclic.
Generated by search/k6/gen_family_lean.py; the cycle lists are certificates only,
Lean re-derives every fact about them by `decide`.
-/

open SimpleGraph
namespace Erdos1016

def chordsF48 : List (Nat × Nat) := [(0,2), (0,41), (1,13), (3,42), (4,31), (40,43)]
def adjF48 (a b : Fin 48) : Bool := adjB 48 chordsF48 a.val b.val
def GF48 : SimpleGraph (Fin 48) :=
  SimpleGraph.fromRel (fun u v => adjB 48 chordsF48 u.val v.val = true)
theorem adjF48_irrefl : ∀ a : Fin 48, adjF48 a a = false := by decide
theorem adjF48_spec (a b : Fin 48) (h : adjF48 a b = true) : GF48.Adj a b := by
  unfold GF48
  rw [SimpleGraph.fromRel_adj]
  refine ⟨fun hab => ?_, Or.inl h⟩
  subst hab
  rw [adjF48_irrefl] at h
  exact Bool.false_ne_true h

def cyclesF48 : List (List Nat) := [
  [0, 1, 2],
  [41, 40, 43, 42],
  [0, 2, 3, 42, 41],
  [0, 1, 2, 3, 42, 41],
  [0, 2, 3, 42, 43, 40, 41],
  [0, 1, 2, 3, 42, 43, 40, 41],
  [0, 47, 46, 45, 44, 43, 42, 3, 2],
  [0, 1, 2, 3, 42, 43, 44, 45, 46, 47],
  [0, 47, 46, 45, 44, 43, 40, 41, 42, 3, 2],
  [0, 1, 2, 3, 42, 41, 40, 43, 44, 45, 46, 47],
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 42, 41],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 42, 43, 40, 41],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 42, 41],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 42, 43, 44, 45, 46, 47],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 44, 45, 46, 47],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 42, 41, 40, 43, 44, 45, 46, 47],
  [0, 1, 2, 3, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 42, 41],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 3, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 44, 45, 46, 47],
  [0, 47, 46, 45, 44, 43, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2],
  [0, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
  [0, 47, 46, 45, 44, 43, 42, 3, 4, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 4, 3, 42, 41, 40, 43, 44, 45, 46, 47],
  [0, 47, 46, 45, 44, 43, 40, 41, 42, 3, 4, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 42, 41],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 3, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 44, 45, 46, 47],
  [0, 47, 46, 45, 44, 43, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
  [0, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2],
  [0, 47, 46, 45, 44, 43, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 1, 2, 3, 42, 41],
  [41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 42],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 42, 41],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 42, 41],
  [0, 47, 46, 45, 44, 43, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 44, 45, 46, 47],
  [0, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]
]
def cyclesF48F : List (List (Fin 48)) :=
  cyclesF48.map (List.map (fun v : ℕ => (⟨v % 48, Nat.mod_lt v (by decide)⟩ : Fin 48)))

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem candidatesF48 : (List.range' 3 (48 - 2)).all (fun ℓ => cyclesF48F.any (fun l =>
    (l.length == ℓ) && decide l.Nodup && chainB adjF48 l && closesB adjF48 l)) = true := by decide

theorem isPancyclic_GF48 : IsPancyclic GF48 :=
  isPancyclic_of_candidates GF48 adjF48 adjF48_spec cyclesF48F candidatesF48

def csF48 : Finset (Sym2 (Fin 48)) := {s(0,2), s(0,41), s(1,13), s(3,42), s(4,31), s(40,43)}
set_option maxHeartbeats 0 in
theorem csF48_card : csF48.card = 6 := by decide

-- `decide` over all pairs of `Fin 48`: the n = 56 template ran just inside the default
-- heartbeat and recursion limits, n >= 60 does not (W60/W64/W66 failed at these lines on
-- 2026-09-19 22:58), so both limits are lifted for this kernel computation.
set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem adjF48_iff (a b : Fin 48) :
    (adjF48 a b = true ∨ adjF48 b a = true) ↔
      ((b.val = (a.val + 1) % 48 ∨ a.val = (b.val + 1) % 48) ∨ s(a, b) ∈ csF48) := by
  revert a b
  decide

theorem GF48_eq : baseCycle 48 ⊔ SimpleGraph.fromEdgeSet (↑csF48 : Set (Sym2 (Fin 48))) = GF48 := by
  ext a b
  simp only [SimpleGraph.sup_adj, baseCycle, GF48, SimpleGraph.fromRel_adj,
    SimpleGraph.fromEdgeSet_adj, Finset.mem_coe]
  have h := adjF48_iff a b
  unfold adjF48 at h
  constructor
  · rintro (⟨hne, hc⟩ | ⟨hm, hne⟩)
    · exact ⟨hne, h.2 (Or.inl hc)⟩
    · exact ⟨hne, h.2 (Or.inr hm)⟩
  · rintro ⟨hne, hadj⟩
    rcases h.1 hadj with hc | hm
    · exact Or.inl ⟨hne, hc⟩
    · exact Or.inr ⟨hm, hne⟩

theorem csF48_disjoint : ∀ e ∈ csF48, e ∉ (baseCycle 48).edgeSet := by
  intro e he
  simp only [csF48, Finset.mem_insert, Finset.mem_singleton] at he
  rcases he with rfl | rfl | rfl | rfl | rfl | rfl <;>
    simp [SimpleGraph.mem_edgeSet, baseCycle, SimpleGraph.fromRel_adj]

/-- `h(48) ≤ 6`, by the family member at n = 48. -/
theorem pancyclicWithChords_F48 : PancyclicWithChords 48 6 :=
  ⟨csF48, csF48_card, csF48_disjoint, by rw [GF48_eq]; exact isPancyclic_GF48⟩

end Erdos1016
